export const PRESET_INPUTS = [
  `The judge could scarcely believe the figures. Reviewing the request for legal fees by Skadden, the New York-based law firm, the US District Court Judge Leonard Sand ‘shuddered to think’ that any one lawyer could work so relentlessly. Margaret Enloe, a second-year associate, had logged 78.5 billable hours working for a client over a five-day stretch. After a 17-hour day, she had trudged back to the office the next morning – and gone on to bill 24 hours straight. Enloe shrugged off the judge’s disbelief. ‘I’m a fairly high-energy-level person,’ she said. ‘I worked more than one 24-hour day when I was at Skadden.’

  That stamina, however, did not make for a long career at the firm. Enloe would not go on to earn a coveted election to partnership. After two and a half years, she left to become an in-house attorney at an accounting firm. ‘I needed to change something. I could not keep going at that pace,’ she told me later. ‘It felt unsustainable.’

  Extreme as her work conditions sounded to the judge, Enloe’s experience was becoming the norm at the United States’ largest law firms in the 1980s. Many began to ask associates to bill more hours: 2,500 or even 3,000 per year. Even as young lawyers worked longer – spending 11 or 12 hours every day, including weekends, at the office – they rarely, if ever, enjoyed training by senior attorneys. Instead, they were given menial tasks, like proofreading or document review, with no idea of how it fit into the big picture. Meanwhile, the chances of making partner grew narrower year after year. By the early 2000s, the five-year attrition rate at large firms would rise above 80 per cent.`,

  //

  `I don’t feel like I have a self. Most people I encounter speak about their experience as if they have an internal centre of awareness – something inside doing the perceiving and feeling, a centre to their subjective experience. And most people seem to connect this intuitive sense of a singular self to who they were yesterday, last month, last year – to a continuously unfolding life-story stretching back to their earliest childhood memories. I’ve always struggled to relate to people with such seemingly full and wholesome selves and coherent life narratives. When I look inward, I find no locus of awareness. There doesn’t seem to be anyone or anything at the centre in me, nothing identifiable that is generating or receiving experience; only thoughts and feelings that don’t seem anchored to anything, changing patterns of energy that are simply happening. I don’t remember much from my past either. When I recall it, it comes to my mind mostly as facts – CV-like points that are useful for functioning socially and professionally but with which I feel little emotional connection.

  Nonetheless, I’ve always been drawn to people with voluminous self-conceptions and coherent life-stories. Indeed, I’ve spent a good portion of my professional life as a literary scholar and critic with a focus specifically on life-writing. Karl Ove Knausgård’s My Struggle (2009-11) was the primary example I used for my master’s thesis on autofiction. Over the 3,000-plus pages of this six-volume work, the Norwegian author tracks his identity all the way from childhood to his adult self in the present moment of writing, connecting events from his entire life into one continuous narrative. It is perhaps the most extensive reconstruction of an individual’s personal history in literature, the most solid manifestation of narrative identity – a veritable opus of the continuous self.`,

  //

  `It’s Monday morning at the lab and I have a team presentation due in two hours. I open my laptop intending to tweak a figure, then notice a paper I’d bookmarked. That paper cites another, which leads me to one of the authors’ new preprints. Soon I find myself with 27 tabs open, three half-formed ideas scribbled in my notebook, and a new app downloaded to prototype something that has nothing to do with my presentation.

  I know I should stop and I can feel the time pressure building, but the pull to wander is too strong – almost physical. Just five more minutes, I promise to myself, and I’ll return my attention to the ‘real’ work. Only when my anxiety becomes impossible to ignore do I force myself to come back to the slides.

  This little dance isn’t unusual for me and the millions of other people who can spend hours in deep, almost joyful focus when a question grabs our attention, but who can also derail ourselves completely when we hear about a shiny new idea. For a long time, I thought this was a personal failure of discipline, a quirk I needed to manage better. It’s only when I started working at the ADHD Research Lab at King’s College London that I came to believe it might be something else entirely.`,

  //

  `The art market likes certainty. It prefers painters’ names printed in bold type, dates fixed neatly to a decade, values pinned confidently to price estimates. Yet behind this appearance of assurance lies an industry structured around risk. Enormous sums of money change hands on the basis of attribution (who created this work), and attribution itself often rests on a fragile, negotiated consensus or the determined opinion of one or more experts (some of them more self-proclaimed than objectively expert) rather than an established fact.

  A single name on a museum label can anchor the value of an artwork, determine its place in art history and shape scholarly narratives for generations. Change that name, and the consequences ripple outward. A painting can lose tens of millions in value. Is the world’s most expensive painting, Salvator Mundi (‘Saviour of the World’), indeed by Leonardo da Vinci, as many of the top Leonardo scholars confirm? Its last sale price was $450.3 million in 2017 at Christie’s. But scholars of equal renown are convinced that it is a derivative work, not by Leonardo at all, in which case it might be worth only $450,000. That’s quite a difference for an opinion to make. Enough question marks have been thrown up around Salvator Mundi that the painting has yet to be displayed in public since its sale. It is thought to have been purchased by proxy by the Saudi crown prince Mohammed bin Salman to become the centrepiece of the Louvre Abu Dhabi, but it is not on display and its location is not now publicly known.`,

  //

  `In the summer of 2017, two biologists set out for Denman Island in British Columbia, Canada, to build a house from scratch. This was not the first time. Years before, they’d built a cabin on the same 40-acre property, a cherished place of respite away from the lab. ‘We made the whole thing with almost no tools,’ Victoria Foe tells me with a playful, nearly mischievous energy. ‘We cut down the trees and made the joints.’ The only motorised device was a large drill the pair put in the refrigerator to cool down between driving dowel holes in the lumber. Foe, renowned for her precise studies of microscopic cells and embryos, debarked logs that would become the main framing posts. Garrett Odell, her life partner and close collaborator, designed the structure in a custom early CAD program he coded for Foe as a Christmas present.

  But that summer things came to an abrupt halt. They had only just begun on the new house when Odell started feeling unwell. By October, he was diagnosed with aggressive liver cancer. ‘He died in May,’ Foe says. ‘It made the light go out in the world.’

  For Foe, a developmental biologist, life and biology are intimately entwined, each motivating and deepening understanding of the other. Rather than turn her away from science, Foe’s grief pulled her back to an observation about the fragility of life she’d carried for decades, ever since the start of her PhD in the late 1960s.`
]
